-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME,
    (B.CITY || ' ' || B.STREET_ADDRESS1 || ' ' || B.STREET_ADDRESS2) 주소,
    SUBSTR(TLNO, 0, 3) ||'-'|| SUBSTR(TLNO, 4, 4) ||'-'|| SUBSTR(TLNO, 8, 4) AS 전화번호
FROM
(SELECT DISTINCT WRITER_ID, COUNT(BOARD_ID) AS COUNT
FROM USED_GOODS_BOARD 
GROUP BY WRITER_ID
HAVING COUNT(BOARD_ID) >=3) A, USED_GOODS_USER B

WHERE A.WRITER_ID = B.USER_ID
ORDER BY USER_ID DESC;