-- 코드를 입력하세요
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS,
B.AVG_SCORE AS SCORE
FROM REST_INFO A,
(SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS AVG_SCORE
FROM REST_REVIEW
GROUP BY REST_ID) B
WHERE A.REST_ID = B.REST_ID
AND A.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, A.FAVORITES DESC;