-- 코드를 입력하세요
SELECT B.YEAR, B.MONTH, A.GENDER, COUNT(DISTINCT A.USER_ID) AS USERS
FROM
USER_INFO A,

(SELECT *, EXTRACT(YEAR FROM SALES_DATE) AS YEAR, EXTRACT(MONTH FROM SALES_DATE) AS MONTH
FROM ONLINE_SALE) B

WHERE A.USER_ID = B.USER_ID
AND A.GENDER IS NOT NULL
GROUP BY B.YEAR, B.MONTH, A.GENDER
ORDER BY YEAR, MONTH, GENDER;