-- 아직 입양 못 간 동물
-- 가장 오래 잇었던 동물 3마리
-- 이름, 보호 시작일
-- 시작일 오름차순

SELECT NAME, DATETIME
FROM ANIMAL_INS 
WHERE ANIMAL_ID NOT IN 

(SELECT ANIMAL_ID
FROM ANIMAL_OUTS)

ORDER BY DATETIME ASC
FETCH FIRST 3 ROWS ONLY;