-- 코드를 입력하세요
-- 생산일자가 2022년 5월
-- select 식품 id, 식품이름, 총매출
-- 정렬 -> 총 매출 내림차, 식품 id 오름차
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, (A.PRICE * B.SUM) AS TOTAL_SALES
FROM

(SELECT PRODUCT_ID, PRODUCT_NAME, PRICE
FROM FOOD_PRODUCT) A,

(SELECT DISTINCT PRODUCT_ID, SUM(AMOUNT) AS SUM
FROM FOOD_ORDER
WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY PRODUCT_ID) B

WHERE A.PRODUCT_ID = B.PRODUCT_ID

ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;