-- 코드를 입력하세요
SELECT A.CATEGORY, A.PRICE, A.PRODUCT_NAME
FROM

FOOD_PRODUCT A,

(SELECT CATEGORY, MAX(PRICE) AS PRICE
FROM FOOD_PRODUCT
GROUP BY CATEGORY) B

WHERE A.CATEGORY = B.CATEGORY
AND A.PRICE = B.PRICE
AND A.CATEGORY IN ('식용유', '과자', '국', '김치')
ORDER BY PRICE DESC;